name: Deploy React Movie App to Azure Static Storage

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      REACT_APP_AI_KEY: ${{ secrets.REACT_APP_AI_KEY }}
      STORAGE_NAME: ${{ secrets.STORAGE_NAME }}
      CDN_NAME: ${{ secrets.CDN_NAME }}
      CDN_ENDPOINT: ${{ secrets.CDN_ENDPOINT }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --audit-level high

      - name: Build
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage with Azure CLI
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            # Set cache headers for different asset types
            
            # Upload static JS/CSS files with long cache (1 year) - these have content hashes
            az storage blob upload-batch \
              --account-name "reactmoviedb" \
              --auth-mode key \
              -d '$web' \
              -s ./build/static \
              --destination-path static \
              --content-cache-control "public, max-age=31536000, immutable"
              --overwrite
            
            # Upload images with medium cache (30 days)
            az storage blob upload-batch \
              --account-name "reactmoviedb" \
              --auth-mode key \
              -d '$web' \
              -s ./build/images \
              --destination-path images \
              --content-cache-control "public, max-age=2592000" || true
              --overwrite
            
            # Upload icons and manifest with medium cache (30 days)
            for file in favicon.ico icon-192.png icon-512.png manifest.json; do
              if [ -f "./build/$file" ]; then
                az storage blob upload \
                  --account-name "reactmoviedb" \
                  --auth-mode key \
                  --container-name '$web' \
                  --name "$file" \
                  --file "./build/$file" \
                  --content-cache-control "public, max-age=2592000"
                  --overwrite
              fi
            done
            
            # Upload index.html with no cache (always fetch latest)
            az storage blob upload \
              --account-name "reactmoviedb" \
              --auth-mode key \
              --container-name '$web' \
              --name "index.html" \
              --file "./build/index.html" \
              --content-cache-control "no-cache, no-store, must-revalidate"
              --overwrite
            
            # Upload service worker with no cache (if exists)
            if [ -f "./build/service-worker.js" ]; then
              az storage blob upload \
                --account-name "reactmoviedb" \
                --auth-mode key \
                --container-name '$web' \
                --name "service-worker.js" \
                --file "./build/service-worker.js" \
                --content-cache-control "no-cache, no-store, must-revalidate"
                --overwrite
            fi

      - name: Logout from Azure
        if: always()
        run: az logout
