name: Deploy React Movie App to Azure Static Storage

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      REACT_APP_AI_KEY: ${{ secrets.REACT_APP_AI_KEY }}
      STORAGE_NAME: ${{ secrets.STORAGE_NAME }}
      CDN_NAME: ${{ secrets.CDN_NAME }}
      CDN_ENDPOINT: ${{ secrets.CDN_ENDPOINT }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage with Azure CLI
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name "KartonReactMovieDB" --auth-mode key -d '$web' -s ./build

      - name: Logout from Azure
        if: always()
        run: az logout
